### ISSUE TITLE
Requirements Model Architecture - Ensemble

### ISSUE THREAD

**Issue by Tsebeb** [ContinualAI/clvision-challenge-2023#11]
Hi,

I was wondering wether it is allowed within the competition to build an ensemble of multiple SlimResnet18 networks as long as they fit within the Memory Budget. For example having multiple frozen versions for the SlimResnet18 that learn a single head at the end?
Or is it intented in the way that each sample only passes through the backbone/SlimResnet18 once?
Kind Regards

**Comment by HamedHemati** [comment]
Hi @Tsebeb

In general both multi-pass inference and model ensembles with the same backbone are allowed. However, the total GPU memory usage **when all models are transferred to the GPU**, shouldn't exceed the limit set for the challenge during training.

**Comment by Tsebeb** [comment]
@neuperc thanks a lot for the quick response.

Another quick questions regarding DataAugmentation. In the Avalanche Framework this is handled via the transform_groups in the individual streams correct? Is it allowed to add modify those or where would be the best point to add those for training?

**Comment by HamedHemati** [comment]
> Another quick questions regarding DataAugmentation. In the Avalanche Framework this is handled via the transform_groups in the individual streams correct?

It's handled via transform groups in individual experiences. For this challenge, we have set default transformations for the datasets of all experiences in the stream as below:

``` python
train_transform = transforms.Compose(
        [
            transforms.RandomCrop(32, padding=4),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
            transforms.Normalize(
                (0.5071, 0.4865, 0.4409), (0.2673, 0.2564, 0.2762)
            ),
        ]
    )
```

But you are allowed you change the transformations as you want. You can also change the data loader to adapt it to your strategy.

> where would be the best point to add those for training?

For more details about dataset transformations in Avalanche you can check this link: 
https://avalanche.continualai.org/how-tos/avalanchedataset/avalanche-transformations#replacing-transformations

**Comment by Tsebeb** [comment]
thank you @neuperc
