### ISSUE TITLE
Default dataset configuration may be set wrongly?

### ISSUE THREAD

**Issue by M1andy** [ContinualAI/clvision-challenge-2023#2]
Hi, when I tried to figure out the default dataset settings, I found something confused. In the `benchmark.train_stream`, the variable `experience.scenario.seen_classes` is `[34, 51, ....]`, which is smaller at the beginning and then increases to 100, just like the website shows. 

But when I tried to write a plugin, I found that the strategy has the attribute `mb_y`, which is the current mini-batch target, and it has much more classes then it should be. It has around **85 to 95** classes along the whole training, even at the first experience, and I think it was set wrongly. 

Can anyone explain that to me? Or I just misunderstood the dataset settings?

**Comment by HamedHemati** [comment]
Hi @M1andy 

The initial config was not a working config, sorry for the confusion. I've added a test configuration now if you want to test the code. You can pull the latest changes, and it should work as expected. 

To print present classes in each experience, you can run the code below and initializing the benchmark:

```python
for experience in benchmark.train_stream:
        print(experience.classes_in_this_experience)

```
The final challenge configs will be added in a few days.

**Comment by M1andy** [comment]
> Hi @M1andy
> 
> The initial config was not a working config, sorry for the confusion. I've added a test configuration now if you want to test the code. You can pull the latest changes, and it should work as expected.
> 
> To print present classes in each experience, you can run the code below and initializing the benchmark:
> 
> ```python
> for experience in benchmark.train_stream:
>         print(experience.classes_in_this_experience)
> ```
> 
> The final challenge configs will be added in a few days.

Thank you for the explanation, now the config makes sense
