### ISSUE TITLE
Inconsistent hardware limitations

### ISSUE THREAD

**Issue by zugexiaodui** [ContinualAI/clvision-challenge-2023#3]
The hardware limitations mentioned on the website are not consistent with those in the code. Is it allowed to modify the code?
![image](https://user-images.githubusercontent.com/30652916/226503556-b1a68515-7b4f-4ae6-afe3-cbe54dcd5820.png)
![image](https://user-images.githubusercontent.com/30652916/226503607-a15a25f6-1605-49f2-883a-d7bdc4feb7ac.png)

**Comment by HamedHemati** [comment]
Hi @zugexiaodui. Thanks for reporting the difference. The values in the code are the correct ones. The values on the website are fixed now.

The hardware usage must remain in the specified range, therefore you're expected not to change the values.

**Comment by zugexiaodui** [comment]
Thank you for your timely response！
