### ISSUE TITLE
Can I scale the image to a larger resolution?

### ISSUE THREAD

**Issue by zugexiaodui** [ContinualAI/clvision-challenge-2023#6]
The default resolution of the input image is 32*32. Can I scale the image to a larger resolution? To this end, the code of SlimResNet18 will be modified slightly (*i.e.* `out = relu(self.bn1(self.conv1(x.view(bsz, 3, 32, 32))))`). Is it allowed or not?

**Comment by HamedHemati** [comment]
@zugexiaodui You are allowed to apply any transformation to the images provided by the streams as long as the base architecture layers are not modified. Changing the input size requires changing the kernel size of the average pooling layer, therefore it's not allowed. We need to compare all strategies using the same base architecture.
Also note that if you want to apply other (allowed) transformations for test time, you need to override the `forward` function and add the transformations there to ensure that the strategy applies them before making prediction on test images.

**Comment by zugexiaodui** [comment]
I got it. Thank you for your explanation!
