### ISSUE TITLE
Question about the usage of replay buffer

### ISSUE THREAD

**Issue by Cklwanfifa** [ContinualAI/clvision-challenge-2023#8]
Hi, I noticed that on the website, it is mentioned that 

> Replay Buffer: Replay buffers may not be used to store dataset samples. However, buffers may be used to store any form of data representation, such as the model's internal representations. 

Does it mean that we are not allowed to use naive ReplayPlugin, but we can use GenerativeReplayPlugin?

**Comment by HamedHemati** [comment]
Hi @Cklwanfifa. 

Just to make it clear:
1- Storing the dataset samples (raw samples) in a buffer is not allowed.
2- Participants are also not allowed to use external data.

This means that generative replay with a pre-trained generator (i.e. a generator trained on external data) is not allowed. However, if the generative model is trained over time in the continual learning process, using the stream data, then it's fine.
