### ISSUE TITLE
Question about modifying the classifier

### ISSUE THREAD

**Issue by ShiWuxuan** [ContinualAI/clvision-challenge-2023#9]
The code gives a classifier with an output dimension of 100, can it be augmented？For example, modify the output dimension to 200.

**Comment by HamedHemati** [comment]
Hi @ShiWuxuan ,

Augmenting the model with additional modules is allowed. Increasing the output dimension can be considered as augmenting the output layer with additional output modules, so it's fine.
Please note that if the inference step is affected by the change, it needs to be implemented in the `forward()` function of the strategy.
